from __future__ import annotations

from typing import Any


COMMON_PATIENT_FIELDS: list[dict[str, Any]] = [
    {"key": "patient_name", "label": "患者姓名", "section": "基本信息", "required": True, "input_type": "text"},
    {"key": "gender", "label": "性别", "section": "基本信息", "required": False, "input_type": "text"},
    {"key": "age", "label": "年龄", "section": "基本信息", "required": False, "input_type": "number"},
    {"key": "department_name", "label": "科别", "section": "基本信息", "required": False, "input_type": "text"},
    {"key": "bed_no", "label": "床号", "section": "基本信息", "required": True, "input_type": "text"},
    {"key": "mrn", "label": "病案号", "section": "基本信息", "required": False, "input_type": "text"},
    {"key": "inpatient_no", "label": "住院号", "section": "基本信息", "required": False, "input_type": "text"},
]


STANDARD_FORM_DEFINITIONS: dict[str, dict[str, Any]] = {
    "nursing_note": {
        "id": "standard-nursing-note",
        "name": "护理记录单",
        "standard_family": "用户导入模板 / 护理文书规范",
        "description": "用于病区常规护理记录、生命体征记录、出入量记录和特殊情况记录。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/护理记录单.docx",
        ],
        "sections": [
            {"key": "basic", "title": "基本信息"},
            {"key": "vitals", "title": "生命体征"},
            {"key": "io", "title": "出入量"},
            {"key": "special", "title": "特殊情况记录"},
            {"key": "signature", "title": "签名信息"},
        ],
        "fields": COMMON_PATIENT_FIELDS
        + [
            {"key": "chart_date", "label": "日期", "section": "基本信息", "required": True, "input_type": "date"},
            {"key": "current_time", "label": "时间", "section": "基本信息", "required": True, "input_type": "datetime"},
            {"key": "consciousness", "label": "意识", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "temperature_value", "label": "T(℃)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "pulse_value", "label": "P(次/分)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "heart_rate_value", "label": "HR(次/分)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "respiratory_rate", "label": "R(次/分)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "blood_pressure", "label": "BP(mmHg)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "spo2_value", "label": "SpO2(%)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "cvp_value", "label": "CVP(cmH2O)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "blood_glucose_value", "label": "血糖(mmol/L)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "intake_summary", "label": "入量", "section": "出入量", "required": False, "input_type": "textarea"},
            {"key": "output_summary", "label": "出量", "section": "出入量", "required": False, "input_type": "textarea"},
            {"key": "special_notes", "label": "特殊情况记录", "section": "特殊情况记录", "required": True, "input_type": "textarea"},
            {"key": "requested_by", "label": "护士签名", "section": "签名信息", "required": True, "input_type": "text"},
            {"key": "supervisor_sign", "label": "上级签名", "section": "签名信息", "required": False, "input_type": "text"},
        ],
    },
    "temperature_chart": {
        "id": "standard-temperature-chart",
        "name": "体温单",
        "standard_family": "用户导入模板 / 生命体征记录",
        "description": "用于体温、脉搏、呼吸、疼痛、血压、尿量及总入出量等日常记录。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/体温单1.docx",
        ],
        "sections": [
            {"key": "basic", "title": "基本信息"},
            {"key": "timeline", "title": "时间轴信息"},
            {"key": "vitals", "title": "生命体征"},
            {"key": "measurements", "title": "扩展记录"},
        ],
        "fields": COMMON_PATIENT_FIELDS
        + [
            {"key": "admission_date", "label": "入院日期", "section": "基本信息", "required": True, "input_type": "date"},
            {"key": "chart_date", "label": "记录日期", "section": "时间轴信息", "required": True, "input_type": "date"},
            {"key": "hospital_day", "label": "住院天数", "section": "时间轴信息", "required": False, "input_type": "text"},
            {"key": "post_op_day", "label": "术后天数", "section": "时间轴信息", "required": False, "input_type": "text"},
            {"key": "current_time", "label": "测量时间", "section": "生命体征", "required": True, "input_type": "datetime"},
            {"key": "temperature_value", "label": "体温(℃)", "section": "生命体征", "required": True, "input_type": "text"},
            {"key": "pulse_value", "label": "脉搏(次/分)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "respiratory_rate", "label": "呼吸(次/分)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "pain_score", "label": "疼痛强度", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "blood_pressure_morning", "label": "血压(上午)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "blood_pressure_noon", "label": "血压(中午)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "blood_pressure_afternoon", "label": "血压(下午)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "blood_pressure_night", "label": "血压(晚上)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "height", "label": "身高(cm)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "weight", "label": "体重(kg)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "urine_volume", "label": "尿量(ml)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "intake_total", "label": "总入量(ml)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "output_total", "label": "总出量(ml)", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "stool_count", "label": "大便次数", "section": "扩展记录", "required": False, "input_type": "text"},
            {"key": "spoken_text", "label": "备注", "section": "扩展记录", "required": False, "input_type": "textarea"},
            {"key": "requested_by", "label": "记录护士", "section": "扩展记录", "required": True, "input_type": "text"},
        ],
    },
    "surgical_count_record": {
        "id": "standard-surgical-count-record",
        "name": "手术物品清单",
        "standard_family": "用户导入模板 / 手术室护理记录",
        "description": "用于手术前后器械、纱布、引流管及交接物品记录。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/手术物品清单.docx",
        ],
        "sections": [
            {"key": "basic", "title": "手术信息"},
            {"key": "preop", "title": "术前准备"},
            {"key": "count", "title": "清点结果"},
            {"key": "postop", "title": "术毕及交接"},
        ],
        "fields": [
            {"key": "patient_name", "label": "患者姓名", "section": "手术信息", "required": True, "input_type": "text"},
            {"key": "gender", "label": "性别", "section": "手术信息", "required": False, "input_type": "text"},
            {"key": "age", "label": "年龄", "section": "手术信息", "required": False, "input_type": "number"},
            {"key": "chart_date", "label": "手术日期", "section": "手术信息", "required": True, "input_type": "date"},
            {"key": "operation_name", "label": "手术名称", "section": "手术信息", "required": True, "input_type": "text"},
            {"key": "preop_preparation", "label": "术前准备", "section": "术前准备", "required": False, "input_type": "textarea"},
            {"key": "venous_access", "label": "静脉通道", "section": "术前准备", "required": False, "input_type": "text"},
            {"key": "catheter_status", "label": "导尿情况", "section": "术前准备", "required": False, "input_type": "text"},
            {"key": "drug_allergy", "label": "药物过敏史", "section": "术前准备", "required": False, "input_type": "textarea"},
            {"key": "puncture_site", "label": "静脉穿刺部位", "section": "术前准备", "required": False, "input_type": "text"},
            {"key": "position_fixation", "label": "体位及固定方法", "section": "术前准备", "required": False, "input_type": "textarea"},
            {"key": "electrotome_status", "label": "电刀使用情况", "section": "术前准备", "required": False, "input_type": "text"},
            {"key": "specimen_status", "label": "标本送病理情况", "section": "术前准备", "required": False, "input_type": "text"},
            {"key": "special_record", "label": "特殊情况记录", "section": "术前准备", "required": False, "input_type": "textarea"},
            {"key": "instrument_count", "label": "器械清点", "section": "清点结果", "required": True, "input_type": "textarea"},
            {"key": "dressing_count", "label": "敷料清点", "section": "清点结果", "required": True, "input_type": "textarea"},
            {"key": "special_item_count", "label": "特殊物品清点", "section": "清点结果", "required": False, "input_type": "textarea"},
            {"key": "integrity_check", "label": "完整性核对结果", "section": "清点结果", "required": True, "input_type": "textarea"},
            {"key": "operation_end_status", "label": "术毕情况", "section": "术毕及交接", "required": False, "input_type": "textarea"},
            {"key": "blood_pressure", "label": "出室血压", "section": "术毕及交接", "required": False, "input_type": "text"},
            {"key": "pulse_value", "label": "出室脉搏", "section": "术毕及交接", "required": False, "input_type": "text"},
            {"key": "drainage_status", "label": "引流管放置情况", "section": "术毕及交接", "required": False, "input_type": "textarea"},
            {"key": "handover_items", "label": "物品交接", "section": "术毕及交接", "required": False, "input_type": "textarea"},
            {"key": "requested_by", "label": "护士签名", "section": "术毕及交接", "required": True, "input_type": "text"},
        ],
    },
    "critical_patient_nursing_record": {
        "id": "standard-critical-patient-nursing-record",
        "name": "病重（病危）患者护理记录单",
        "standard_family": "护理文书规范 / 危重症护理",
        "description": "用于危重患者生命体征、病情观察、护理措施及出入量连续记录。",
        "schema_version": "2026.04",
        "source_refs": [
            "system://critical_patient_nursing_record",
        ],
        "sections": [
            {"key": "basic", "title": "基本信息"},
            {"key": "vitals", "title": "生命体征"},
            {"key": "io", "title": "出入量"},
            {"key": "care", "title": "病情观察与护理"},
            {"key": "signature", "title": "签名信息"},
        ],
        "fields": COMMON_PATIENT_FIELDS
        + [
            {"key": "current_time", "label": "记录时间", "section": "生命体征", "required": True, "input_type": "datetime"},
            {"key": "diagnoses", "label": "主要诊断", "section": "病情观察与护理", "required": True, "input_type": "textarea"},
            {"key": "temperature_value", "label": "体温(℃)", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "pulse_value", "label": "心率/脉搏", "section": "生命体征", "required": True, "input_type": "text"},
            {"key": "respiratory_rate", "label": "呼吸", "section": "生命体征", "required": True, "input_type": "text"},
            {"key": "spo2_value", "label": "SpO2", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "blood_pressure", "label": "血压", "section": "生命体征", "required": False, "input_type": "text"},
            {"key": "intake_total", "label": "入量", "section": "出入量", "required": False, "input_type": "text"},
            {"key": "output_total", "label": "出量", "section": "出入量", "required": False, "input_type": "text"},
            {"key": "observation_summary", "label": "病情观察", "section": "病情观察与护理", "required": True, "input_type": "textarea"},
            {"key": "risk_level", "label": "风险等级", "section": "病情观察与护理", "required": True, "input_type": "text"},
            {"key": "risk_tags", "label": "重点风险", "section": "病情观察与护理", "required": False, "input_type": "textarea"},
            {"key": "spoken_text", "label": "护理措施与效果", "section": "病情观察与护理", "required": True, "input_type": "textarea"},
            {"key": "pending_tasks", "label": "下一班观察重点", "section": "病情观察与护理", "required": False, "input_type": "textarea"},
            {"key": "requested_by", "label": "护士签名", "section": "签名信息", "required": True, "input_type": "text"},
        ],
    },
    "transfusion_nursing_record": {
        "id": "standard-transfusion-record",
        "name": "输血记录单",
        "standard_family": "用户导入模板 / 输血护理记录",
        "description": "用于输血前查对、巡察记录、输血起止时间及输血反应记录。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/输血记录单.docx",
        ],
        "sections": [
            {"key": "basic", "title": "基本信息"},
            {"key": "precheck", "title": "输血前查对"},
            {"key": "monitoring", "title": "输血中巡察"},
            {"key": "completion", "title": "输血结束"},
        ],
        "fields": [
            {"key": "patient_name", "label": "患者姓名", "section": "基本信息", "required": True, "input_type": "text"},
            {"key": "gender", "label": "性别", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "age", "label": "年龄", "section": "基本信息", "required": False, "input_type": "number"},
            {"key": "ethnicity", "label": "民族", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "department_name", "label": "科别", "section": "基本信息", "required": True, "input_type": "text"},
            {"key": "ward_name", "label": "病室", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "bed_no", "label": "床号", "section": "基本信息", "required": True, "input_type": "text"},
            {"key": "inpatient_no", "label": "住院号", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "transfusion_reaction_history", "label": "输血反应史", "section": "基本信息", "required": False, "input_type": "textarea"},
            {"key": "precheck_summary", "label": "输血前查对内容", "section": "输血前查对", "required": True, "input_type": "textarea"},
            {"key": "requested_by", "label": "查对人签字", "section": "输血前查对", "required": True, "input_type": "text"},
            {"key": "double_checker", "label": "复核人签字", "section": "输血前查对", "required": True, "input_type": "text"},
            {"key": "temperature_before", "label": "输血前体温", "section": "输血中巡察", "required": False, "input_type": "text"},
            {"key": "blood_pressure_before", "label": "输血前血压", "section": "输血中巡察", "required": False, "input_type": "text"},
            {"key": "transfusion_start_time", "label": "输血开始时间", "section": "输血中巡察", "required": True, "input_type": "datetime"},
            {"key": "spoken_text", "label": "输血中记录及处理", "section": "输血中巡察", "required": True, "input_type": "textarea"},
            {"key": "transfusion_end_time", "label": "输血结束时间", "section": "输血结束", "required": False, "input_type": "datetime"},
            {"key": "temperature_after", "label": "结束时体温", "section": "输血结束", "required": False, "input_type": "text"},
            {"key": "blood_pressure_after", "label": "结束时血压", "section": "输血结束", "required": False, "input_type": "text"},
            {"key": "actual_transfusion_volume", "label": "实际输入量", "section": "输血结束", "required": False, "input_type": "text"},
            {"key": "transfusion_reaction", "label": "输血反应及处理", "section": "输血结束", "required": False, "input_type": "textarea"},
        ],
    },
    "transfusion_process_record": {
        "id": "standard-transfusion-process-record",
        "name": "临床输血过程记录单",
        "standard_family": "用户导入模板 / 输血过程监测",
        "description": "用于输血过程全程记录、流速记录及不良反应监测。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/输血过程记录单.docx",
        ],
        "sections": [
            {"key": "header", "title": "记录信息"},
            {"key": "patient", "title": "受血者信息"},
            {"key": "blood", "title": "血液信息"},
            {"key": "process", "title": "输血过程"},
            {"key": "remark", "title": "备注"},
        ],
        "fields": [
            {"key": "requested_by", "label": "记录人", "section": "记录信息", "required": True, "input_type": "text"},
            {"key": "double_checker", "label": "复核人", "section": "记录信息", "required": True, "input_type": "text"},
            {"key": "current_time", "label": "记录时间", "section": "记录信息", "required": True, "input_type": "datetime"},
            {"key": "patient_name", "label": "受血者姓名", "section": "受血者信息", "required": True, "input_type": "text"},
            {"key": "mrn", "label": "病案号", "section": "受血者信息", "required": False, "input_type": "text"},
            {"key": "gender", "label": "性别", "section": "受血者信息", "required": False, "input_type": "text"},
            {"key": "age", "label": "年龄", "section": "受血者信息", "required": False, "input_type": "number"},
            {"key": "blood_type", "label": "血型", "section": "受血者信息", "required": False, "input_type": "text"},
            {"key": "rh_type", "label": "Rh血型", "section": "受血者信息", "required": False, "input_type": "text"},
            {"key": "department_name", "label": "科别", "section": "受血者信息", "required": False, "input_type": "text"},
            {"key": "ward_name", "label": "病区", "section": "受血者信息", "required": False, "input_type": "text"},
            {"key": "bed_no", "label": "床号", "section": "受血者信息", "required": True, "input_type": "text"},
            {"key": "transfusion_priority", "label": "输血性质", "section": "血液信息", "required": False, "input_type": "text"},
            {"key": "donor_barcode", "label": "供血者条码号", "section": "血液信息", "required": False, "input_type": "text"},
            {"key": "blood_component", "label": "血液成分", "section": "血液信息", "required": True, "input_type": "text"},
            {"key": "blood_volume", "label": "血量(ml)", "section": "血液信息", "required": False, "input_type": "text"},
            {"key": "transfusion_start_time", "label": "开始时间", "section": "输血过程", "required": True, "input_type": "datetime"},
            {"key": "first_stage_rate", "label": "初始流速", "section": "输血过程", "required": False, "input_type": "text"},
            {"key": "first_stage_reaction", "label": "初始不良反应", "section": "输血过程", "required": False, "input_type": "text"},
            {"key": "second_stage_rate", "label": "中段流速", "section": "输血过程", "required": False, "input_type": "text"},
            {"key": "second_stage_reaction", "label": "中段不良反应", "section": "输血过程", "required": False, "input_type": "text"},
            {"key": "transfusion_end_time", "label": "结束时间", "section": "输血过程", "required": False, "input_type": "datetime"},
            {"key": "transfusion_reaction", "label": "末段不良反应", "section": "输血过程", "required": False, "input_type": "textarea"},
            {"key": "spoken_text", "label": "备注", "section": "备注", "required": False, "input_type": "textarea"},
        ],
    },
    "glucose_record": {
        "id": "standard-glucose-record",
        "name": "血糖记录单",
        "standard_family": "用户导入模板 / POCT记录",
        "description": "用于早餐、午餐、晚餐、睡前及随机血糖记录。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/血糖记录单.docx",
        ],
        "sections": [
            {"key": "basic", "title": "基本信息"},
            {"key": "measurements", "title": "血糖记录"},
            {"key": "remark", "title": "补充说明"},
        ],
        "fields": [
            {"key": "patient_name", "label": "姓名", "section": "基本信息", "required": True, "input_type": "text"},
            {"key": "gender", "label": "性别", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "age", "label": "年龄", "section": "基本信息", "required": False, "input_type": "number"},
            {"key": "department_name", "label": "科别", "section": "基本信息", "required": True, "input_type": "text"},
            {"key": "bed_no", "label": "床号", "section": "基本信息", "required": True, "input_type": "text"},
            {"key": "inpatient_no", "label": "住院号", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "chart_date", "label": "日期", "section": "血糖记录", "required": True, "input_type": "date"},
            {"key": "breakfast_before_glucose", "label": "早餐前(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "breakfast_after_glucose", "label": "早餐后(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "lunch_before_glucose", "label": "午餐前(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "lunch_after_glucose", "label": "午餐后(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "dinner_before_glucose", "label": "晚餐前(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "dinner_after_glucose", "label": "晚餐后(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "bedtime_glucose", "label": "睡前血糖(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "current_time", "label": "随机血糖时间", "section": "血糖记录", "required": False, "input_type": "datetime"},
            {"key": "glucose_value", "label": "随机血糖值(mmol/L)", "section": "血糖记录", "required": False, "input_type": "text"},
            {"key": "spoken_text", "label": "补充说明", "section": "补充说明", "required": False, "input_type": "textarea"},
            {"key": "requested_by", "label": "记录人", "section": "补充说明", "required": True, "input_type": "text"},
        ],
    },
    "nursing_handover_report": {
        "id": "standard-nursing-handover-report",
        "name": "大交班报告",
        "standard_family": "用户导入模板 / 交接班记录",
        "description": "用于病区大交班统计、重点患者和特殊事件交接。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/日夜交班.docx",
        ],
        "sections": [
            {"key": "summary", "title": "交班统计"},
            {"key": "patient", "title": "重点患者"},
            {"key": "events", "title": "特殊事件"},
            {"key": "signature", "title": "签名信息"},
        ],
        "fields": [
            {"key": "department_name", "label": "科室", "section": "交班统计", "required": True, "input_type": "text"},
            {"key": "shift_date", "label": "交班日期", "section": "交班统计", "required": True, "input_type": "date"},
            {"key": "shift_type", "label": "班次", "section": "交班统计", "required": False, "input_type": "text"},
            {"key": "ward_total", "label": "总人数", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "discharge_count", "label": "出院", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "transfer_out_count", "label": "转出", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "admission_count", "label": "入院", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "transfer_in_count", "label": "转入", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "operation_count", "label": "手术/介入", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "tomorrow_operation_count", "label": "明日手术/介入", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "serious_count", "label": "病重", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "critical_count", "label": "病危", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "death_count", "label": "死亡", "section": "交班统计", "required": False, "input_type": "number"},
            {"key": "special_disease_care", "label": "特殊疾病护理", "section": "交班统计", "required": False, "input_type": "textarea"},
            {"key": "other_summary", "label": "其他", "section": "交班统计", "required": False, "input_type": "textarea"},
            {"key": "infectious_report", "label": "传染病报卡", "section": "交班统计", "required": False, "input_type": "textarea"},
            {"key": "bed_no", "label": "床号", "section": "重点患者", "required": False, "input_type": "text"},
            {"key": "patient_name", "label": "姓名", "section": "重点患者", "required": False, "input_type": "text"},
            {"key": "age", "label": "年龄", "section": "重点患者", "required": False, "input_type": "number"},
            {"key": "gender", "label": "性别", "section": "重点患者", "required": False, "input_type": "text"},
            {"key": "inpatient_no", "label": "住院号", "section": "重点患者", "required": False, "input_type": "text"},
            {"key": "diagnoses", "label": "诊断", "section": "重点患者", "required": False, "input_type": "textarea"},
            {"key": "observation_summary", "label": "特殊病情", "section": "重点患者", "required": True, "input_type": "textarea"},
            {"key": "spoken_text", "label": "24小时病情及处理", "section": "重点患者", "required": True, "input_type": "textarea"},
            {"key": "special_events", "label": "特殊事件", "section": "特殊事件", "required": False, "input_type": "textarea"},
            {"key": "requested_by", "label": "交班人签名", "section": "签名信息", "required": True, "input_type": "text"},
            {"key": "receiver_sign", "label": "接班人签名", "section": "签名信息", "required": True, "input_type": "text"},
        ],
    },
    "stroke_tcm_nursing_effect_evaluation": {
        "id": "standard-stroke-tcm-nursing-effect-evaluation",
        "name": "中风（脑梗死急性期）中医护理效果评价表",
        "standard_family": "用户导入模板 / 中医护理评价",
        "description": "用于中风急性期中医辨证分型、护理施护方法及护理效果评价。",
        "schema_version": "2026.04",
        "source_refs": [
            "data/template_imports/various_nursing_records/各种护理记录单/中风（脑梗死急性期）中医护理方案(第二次修订).doc",
        ],
        "sections": [
            {"key": "basic", "title": "基本信息"},
            {"key": "pattern", "title": "辨证分型"},
            {"key": "evaluation", "title": "护理效果评价"},
            {"key": "signature", "title": "签名信息"},
        ],
        "fields": [
            {"key": "hospital_name", "label": "医院", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "patient_name", "label": "患者姓名", "section": "基本信息", "required": True, "input_type": "text"},
            {"key": "gender", "label": "性别", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "age", "label": "年龄", "section": "基本信息", "required": False, "input_type": "number"},
            {"key": "patient_identifier", "label": "ID", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "education_level", "label": "文化程度", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "phone", "label": "电话", "section": "基本信息", "required": False, "input_type": "text"},
            {"key": "admission_date", "label": "入院日期", "section": "基本信息", "required": False, "input_type": "date"},
            {"key": "yang_pattern", "label": "阳类证", "section": "辨证分型", "required": False, "input_type": "textarea"},
            {"key": "yin_pattern", "label": "阴类证", "section": "辨证分型", "required": False, "input_type": "textarea"},
            {"key": "collapse_pattern", "label": "脱证", "section": "辨证分型", "required": False, "input_type": "textarea"},
            {"key": "symptom_name", "label": "主要症状", "section": "护理效果评价", "required": True, "input_type": "text"},
            {"key": "nursing_method", "label": "主要辨证施护方法", "section": "护理效果评价", "required": True, "input_type": "textarea"},
            {"key": "tcm_technique", "label": "中医护理技术", "section": "护理效果评价", "required": False, "input_type": "textarea"},
            {"key": "severity_before_date", "label": "实施前日期", "section": "护理效果评价", "required": False, "input_type": "date"},
            {"key": "severity_before_score", "label": "实施前分数", "section": "护理效果评价", "required": False, "input_type": "text"},
            {"key": "severity_after_date", "label": "实施后日期", "section": "护理效果评价", "required": False, "input_type": "date"},
            {"key": "severity_after_score", "label": "实施后分数", "section": "护理效果评价", "required": False, "input_type": "text"},
            {"key": "effect_evaluation", "label": "效果评价", "section": "护理效果评价", "required": False, "input_type": "textarea"},
            {"key": "spoken_text", "label": "补充说明", "section": "护理效果评价", "required": False, "input_type": "textarea"},
            {"key": "requested_by", "label": "责任护士", "section": "签名信息", "required": True, "input_type": "text"},
        ],
    },
}


DOCUMENT_TYPE_ALIASES: dict[str, str] = {
    "general_nursing_record": "nursing_note",
    "blood_transfusion_nursing_record": "transfusion_nursing_record",
    "blood_glucose_record": "glucose_record",
    "handover_report": "nursing_handover_report",
    "\u62A4\u7406\u8BB0\u5F55\u5355": "nursing_note",
    "\u4F53\u6E29\u5355": "temperature_chart",
    "\u624B\u672F\u7269\u54C1\u6E05\u5355": "surgical_count_record",
    "\u75C5\u91CD\uFF08\u75C5\u5371\uFF09\u60A3\u8005\u62A4\u7406\u8BB0\u5F55\u5355": "critical_patient_nursing_record",
    "\u75C5\u91CD\uFF08\u75C5\u5371\uFF09\u62A4\u7406\u8BB0\u5F55\u5355": "critical_patient_nursing_record",
    "\u75C5\u91CD\u62A4\u7406\u8BB0\u5F55\u5355": "critical_patient_nursing_record",
    "\u75C5\u5371\u62A4\u7406\u8BB0\u5F55\u5355": "critical_patient_nursing_record",
    "\u8F93\u8840\u8BB0\u5F55\u5355": "transfusion_nursing_record",
    "\u4E34\u5E8A\u8F93\u8840\u8FC7\u7A0B\u8BB0\u5F55\u5355": "transfusion_process_record",
    "\u8840\u7CD6\u8BB0\u5F55\u5355": "glucose_record",
    "\u5927\u4EA4\u73ED\u62A5\u544A": "nursing_handover_report",
    "\u65E5\u591C\u4EA4\u73ED": "nursing_handover_report",
    "\u4E2D\u98CE\uFF08\u8111\u6897\u6B7B\u6025\u6027\u671F\uFF09\u4E2D\u533B\u62A4\u7406\u6548\u679C\u8BC4\u4EF7\u8868": "stroke_tcm_nursing_effect_evaluation",
}


def normalize_document_type(document_type: str | None) -> str:
    key = str(document_type or "").strip().lower()
    if key in STANDARD_FORM_DEFINITIONS:
        return key
    return DOCUMENT_TYPE_ALIASES.get(key, "nursing_note")


def get_standard_form_definition(document_type: str) -> dict[str, Any]:
    key = normalize_document_type(document_type)
    return dict(STANDARD_FORM_DEFINITIONS[key])


def get_field_schema(document_type: str) -> list[dict[str, Any]]:
    definition = get_standard_form_definition(document_type)
    return [dict(item) for item in definition.get("fields", [])]


def list_standard_form_definitions() -> list[dict[str, Any]]:
    return [{"document_type": key, **get_standard_form_definition(key)} for key in STANDARD_FORM_DEFINITIONS]
